version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  prepare:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
workflows:
    build-and-test:
      jobs:
        - prepare