version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  prepare:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: v1-dependncies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: v1-dependncies-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - persist_to_workspace: 
          root: .
          paths: node_modules
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: coverage

workflows:
    build-and-test:
      jobs:
        - prepare
        - test: 
            requires: 
              - prepare